(defpackage :xtce
  (:use :cl
		:cxml
		:filesystem-hash-table)
  (:documentation "XTCE")
  (:export
   #:algorithm-set
   #:alias-set
   #:alias-set
   #:ancillary-data-set
   #:ancillary-data-set
   #:bit-location-from-start
   #:bit-rate-in-bips
   #:check-to-lock-good-frames
   #:command-metadata
   #:container-ref
   #:container-set
   #:custom-stream
   #:data-encoding
   #:dereference
   #:dump-xml
   #:entry-list
   #:fixed-frame-stream
   #:format-bool
   #:format-number
   #:format-symbol
   #:frame-length-in-bits
   #:get-size
   #:hamming-distance
   #:header
   #:hex-length-in-bits
   #:instantiate-parameter
   #:inverted
   #:ldb-left
   #:long-description
   #:long-description
   #:make-absolute-time-parameter
   #:make-algorithm-text
   #:make-ancillary-data
   #:make-ancillary-data-set
   #:make-argument-instance-ref
   #:make-array-parameter-ref-entry
   #:make-array-parameter-type
   #:make-base-container
   #:make-binary-data-encoding
   #:make-binary-parameter-type
   #:make-boolean-parameter-type
   #:make-comparison
   #:make-constant
   #:make-container-ref
   #:make-container-ref-entry
   #:make-container-segment-ref-entry
   #:make-count
   #:make-custom-stream
   #:make-decoding-algorithm
   #:make-default-rate-in-stream
   #:make-dimension
   #:make-dynamic-value
   #:make-encoding
   #:make-encoding-algorithm
   #:make-ending-index
   #:make-enumerated-parameter-type
   #:make-enumeration
   #:make-enumeration-alarm
   #:make-epoch
   #:make-external-algorithm
   #:make-fixed
   #:make-fixed-frame-stream
   #:make-fixed-value
   #:make-float-data-encoding
   #:make-float-parameter-type
   #:make-include-condition
   #:make-indirect-parameter-ref-entry
   #:make-input-parameter-instance-ref
   #:make-integer-data-encoding
   #:make-integer-parameter-type
   #:make-leading-size
   #:make-linear-adjustment
   #:make-location-in-container-in-bits
   #:make-long-description
   #:make-next-container
   #:make-offset
   #:make-offset-from
   #:make-parameter
   #:make-parameter-instance-ref
   #:make-parameter-properties
   #:make-parameter-ref-entry
   #:make-parameter-segment-ref-entry
   #:make-polynomial-calibrator
   #:make-rate-in-stream
   #:make-reference-time
   #:make-repeat-entry
   #:make-restriction-criteria
   #:make-sequence-container
   #:make-service
   #:make-service-ref
   #:make-size-in-bits
   #:make-size-range-in-characters
   #:make-space-system
   #:make-spline-point
   #:make-starting-index
   #:make-stream-ref
   #:make-stream-segment-entry
   #:make-string-data-encoding
   #:make-string-parameter-type
   #:make-sync-pattern
   #:make-sync-strategy
   #:make-telemetry-metadata
   #:make-term
   #:make-termination-char
   #:make-unit
   #:mask
   #:max-bit-errors-in-sync-pattern
   #:message-set
   #:name
   #:next-ref
   #:operational-status
   #:parameter-type-set
   #:parent-system
   #:pattern
   #:pattern-length-in-bits
   #:pcm-type
   #:print-bin
   #:print-hex
   #:prompt-new-value
   #:push-ancillary-data
   #:reference-set
   #:root
   #:service-set
   #:short-description
   #:short-description
   #:space-system-list
   #:stream-ref
   #:stream-set
   #:symbol-table
   #:sync-aperture-in-bits
   #:sync-pattern
   #:sync-strategy
   #:sync-strategy
   #:telemetry-metadata
   #:truncate-from-left
   #:truncate-from-left-to-size
   #:variable-frame-stream
   #:verify-to-lock-good-frames
   #:xml-base
   ))

(defpackage :standard-template-constructs
  (:use :cl
		:xtce)
  (:documentation "Standard Template Constructs")
  (:nicknames :stc)
  (:export
   #:CCSDS.AOS.Data-Field
   #:CCSDS.AOS.Data-Field-Type
   #:CCSDS.AOS.Header.Frame-Count-Cycle
   #:CCSDS.AOS.Header.Frame-Count-Cycle-Type
   #:CCSDS.AOS.Header.Frame-Header-Error-Control
   #:CCSDS.AOS.Header.Frame-Header-Error-Control-Type
   #:CCSDS.AOS.Header.Master-Channel-ID
   #:CCSDS.AOS.Header.Master-Channel-ID-Type
   #:CCSDS.AOS.Header.Replay-Flag
   #:CCSDS.AOS.Header.Replay-Flag-Type
   #:CCSDS.AOS.Header.Reserved-Spare
   #:CCSDS.AOS.Header.Reserved-Spare-Type
   #:CCSDS.AOS.Header.Signaling-Field
   #:CCSDS.AOS.Header.Signaling-Field-Type
   #:CCSDS.AOS.Header.Spacecraft-Identifier
   #:CCSDS.AOS.Header.Spacecraft-Identifier-Type
   #:CCSDS.AOS.Header.Version-Number
   #:CCSDS.AOS.Header.Version-Number-Type
   #:CCSDS.AOS.Header.Virtual-Channel-Frame-Count
   #:CCSDS.AOS.Header.Virtual-Channel-Frame-Count-Type
   #:CCSDS.AOS.Header.Virtual-Channel-Frame-Count-Usage-Flag
   #:CCSDS.AOS.Header.Virtual-Channel-Frame-Count-Usage-Flag-Type
   #:CCSDS.AOS.Header.Virtual-Channel-ID
   #:CCSDS.AOS.Header.Virtual-Channel-ID-Type
   #:CCSDS.AOS.Insert-Zone
   #:CCSDS.AOS.Insert-Zone-Type
   #:CCSDS.MPDU.Header.First-Header-Pointer
   #:CCSDS.MPDU.Header.Reserved-Spare
   #:CCSDS.MPDU.Header.Reserved-Spare-Type
   #:CCSDS.MPDU.Packet
   #:CCSDS.MPDU.Packet-Type
   #:CCSDS.MPDU.Packet-Zone
   #:CCSDS.Space-Packet.Header.Application-Process-Identifier
   #:CCSDS.Space-Packet.Header.Application-Process-Identifier-Type
   #:CCSDS.Space-Packet.Header.Packet-Data-Length
   #:CCSDS.Space-Packet.Header.Packet-Data-Length-Type
   #:CCSDS.Space-Packet.Header.Packet-Identification
   #:CCSDS.Space-Packet.Header.Packet-Identification-Type
   #:CCSDS.Space-Packet.Header.Packet-Name
   #:CCSDS.Space-Packet.Header.Packet-Name-Type
   #:CCSDS.Space-Packet.Header.Packet-Sequence-Control-Type
   #:CCSDS.Space-Packet.Header.Packet-Sequence-Count
   #:CCSDS.Space-Packet.Header.Packet-Sequence-Count-Type
   #:CCSDS.Space-Packet.Header.Packet-Transfer-Frame-Version-Number
   #:CCSDS.Space-Packet.Header.Packet-Type
   #:CCSDS.Space-Packet.Header.Packet-Type-Type
   #:CCSDS.Space-Packet.Header.Packet-Version-Number-Type
   #:CCSDS.Space-Packet.Header.Secondary-Header-Flag
   #:CCSDS.Space-Packet.Header.Secondaty-Header-Flag-Type
   #:CCSDS.Space-Packet.Header.Sequence-Control
   #:CCSDS.Space-Packet.Header.Sequence-Flags
   #:CCSDS.Space-Packet.Header.Types
   #:make-space-packet-container
   #:with-ccsds.aos.header.parameters
   #:with-ccsds.aos.header.types
   #:with-ccsds.aos.stream
   #:with-ccsds.mpdu.header.parameters
   #:with-ccsds.space-packet.parameters
   #:with-ccsds.space-packet.header.parameters
   #:with-ccsds.space-packet.header.types
   #:with-ccsds.space-packet.types
   #:with-ccsds-aos-containers
   ))

(defpackage :xtce-engine
  (:use :cl
		:xtce
		:standard-template-constructs
		:lparallel
		:lparallel.queue
		)
  (:documentation "XTCE-Engine")
  (:export
   #:alist->bit-vector
   #:concatenate-bit-arrays
   #:decode
   #:extract-space-packets
   #:fragment-packet
   #:hex-string-to-byte-array
   #:make-mpdu-header
   #:make-networked-fix-frame-stream
   #:monad
   #:pack-arrays-with-padding
   #:pad-bit-vector
   #:uint->bit-vector
   ))

(defpackage :nasa-cfs
  (:use :cl
		:xtce
		:stc
		:xtce-engine)
  (:nicknames :cfs)
  (:documentation "NASA-cFS")
  (:export))
